version: "3.8"

networks:
  stack:

services:
  
  mynewapi:
    image: ${REG}wmsamples-mynewapi:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${REG}webmethods-msr:${TAG}
    environment:
      - BUILTIN_USER_ADMIN_PASSWORD=SomethingStrong123!
    ports:
      - 5555:5555
    networks:
      - stack