version: "3.8"

networks:
  sagnet:

volumes:
  apigw-elasticdata:
  postgres-data:

services:
  
  apigateway:
    image: ${REG}apigateway:${TAG_APIGATEWAY}
    ports:
      - "5556:5555"
      - "9072:9072"
    environment: 
      APIGW_ELASTICSEARCH_TENANTID: apigateway
      JAVA_MIN_MEM: 512m
      JAVA_MAX_MEM: 512m
      IDS_HEAP_SIZE: 512m
      JAVA_OPTS: ""
      RUNTIME_WATT_PROPERTIES: "watt.net.timeout=400 watt.server.threadPool=50 watt.server.threadPoolMin=25 watt.net.maxClientKeepaliveConns=10"
    volumes:
      - apigw-elasticdata:/opt/softwareag/InternalDataStore/data:rw
      - ./licensing/apigateway-licenseKey.xml:/opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml:rw
    hostname: apigateway
    networks:
      - sagnet

  postgres:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sagnet